services:
  db:
    image: mysql:8.0
    container_name: seemoney-mysql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: seemoney-backend
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
        JWT_SECRET: ${JWT_SECRET}
        NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
        NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
volumes:
  mysql-data: