services:
  backend:
    build:
      context: ./backend
    container_name: seemoney-backend
    ports:
      - "8081:8080"   #
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: seemoney-mysql
    restart: always
    ports:
      - "3307:3306"   #
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: